# Generated by Django 4.2.11 on 2024-06-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_received',
            field=models.BooleanField(default=False),
        ),
    ]
